### ISSUE TITLE
Does not work on Philips Xenium W3568 (Android 4.2.2)

### ISSUE THREAD

**Issue by MVoloshin** [limboemu/limbo#2]
System displays message "Unfortunately, Limbo was stopped".
Limbo 0.9.9 & 2.0 Beta work fine. Bochs 2.6.8 too.
Previous version was deleted before installation.

**Comment by limboemu** [comment]
Can you please attach a logcat?

**Comment by limboemu** [comment]
Ignore previous request for logcat, there seems to be an issue with one of the SDL libraries during load time. Will fix in next version coming shortly.

**Comment by HuangLuxuan** [comment]
At line 88 in limbo/src/com/max2idea/android/limbo/main/Config.java,enable it.

**Comment by limboemu** [comment]
Logcat from Emulator running Android 4.2.2

06-15 06:46:32.877: D/dalvikvm(3342): Trying to load lib /data/app-lib/com.limbo.emu.main-1/libSDL2_image.so 0xb4f209f0
06-15 06:46:32.877: D/dalvikvm(3342): Added shared lib /data/app-lib/com.limbo.emu.main-1/libSDL2_image.so 0xb4f209f0
06-15 06:46:32.877: D/dalvikvm(3342): No JNI_OnLoad found in /data/app-lib/com.limbo.emu.main-1/libSDL2_image.so 0xb4f209f0, skipping init
06-15 06:46:32.877: D/dalvikvm(3342): Trying to load lib /data/app-lib/com.limbo.emu.main-1/libmain.so 0xb4f209f0
**06-15 06:46:32.877: E/dalvikvm(3342): dlopen("/data/app-lib/com.limbo.emu.main-1/libmain.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libSDL2_mixer.so" needed by "libmain.so"; caused by load_library(linker.cpp:745): library "libSDL2_mixer.so" not found**

**Comment by limboemu** [comment]
@HuangLuxuan Enabling loading the .so is not prefferable since qemu seems to lock up when sound is enabled. Will attempt to make SDL2_mixer included conditionally in the Android.mk and other makefiles instead until the sound issue is resolved.

**Comment by limboemu** [comment]
Fixed in v2.2.1

**Comment by MVoloshin** [comment]
Problem appeared again in 2.2.2. Please, retest.

**Comment by MVoloshin** [comment]
The same message.

**Comment by HuangLuxuan** [comment]
load library libSDL2_mixer.so before load libmain.so
