### ISSUE TITLE
Sound support

### ISSUE THREAD

**Issue by MVoloshin** [limboemu/limbo#44]
What is wrong with it and when are you going to fix that?

**Comment by ShapeShifter499** [comment]
I second this

**Comment by limboemu** [comment]
I wasn't able to identify the issue, perhaps a thread lock somewhere in SDL since it freezes the vm. Anyway, I'm not sure this is a good thing to pursue since version 0.9.7 and prior show high latency. In addition, android is not offering a low latency sound api, though it might be better with OpenSL ES™.

**Comment by SonsofOcelot** [comment]
I would like to third this. While you don't have access to a low level API there are some users, such as myself, that would like to see it implemented regardless of the higher latencies. Also considering sound is an optional function from the main GUI, end users should have the option of actually triggering it.

**Comment by MVoloshin** [comment]
Ready...
